[package]
name = "git-clone"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.95"
clap = { version = "4.5.28", features = ["derive"] }
colored = "3.0.0"
flate2 = "1.0.35"
hex = "0.4.3"
hex-literal = "0.4.1"
sha1 = "0.10.6"
